[[step]]
mode = 12
gait_id = 0
contact = 0
life_count = 0 #Fake value
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 5000  # Expected execution time of Position interpolation control, For recovery stand need > 5.0S

[[step]]
mode = 62
gait_id = 110
contact = 15
life_count = 0
vel_des = [0.25, 0.0, 0.0]  # 降低速度提升控制精度
rpy_des = [0.0, 0.0, 0.0]
pos_des = [0.3, 0.0, 0.0]   # 缩短目标距离
acc_des = [15.0, 15.0, 15.0, 50.0, 50.0, 15.0]  # 降低加速度
ctrl_point = [0.15, 0.0, 0.42]  # 优化质心位置
foot_pose = [0.25, 0.0, -0.25, 0.0, -0.25, 0.0]  # 精确步幅配置
step_height = [0.18, 0.18]  # 优化抬腿曲线
value = 0
duration = 500 # 延长执行时间

[[step]]
mode = 62
gait_id = 110
contact = 15
life_count = 0
vel_des = [0.25, 0.0, 0.0]
rpy_des = [0.0, 0.0, 0.0]
pos_des = [0.3, 0.0, 0.0]
acc_des = [15.0, 15.0, 15.0, 50.0, 50.0, 15.0]
ctrl_point = [0.15, 0.0, 0.42]
foot_pose = [0.0, 0.0, 0.25, 0.0, 0.25, 0.0]  # 相位交替
step_height = [0.18, 0.18]
value = 0
duration = 500

[[step]]
mode = 62
gait_id = 110
contact = 15
life_count = 0
vel_des = [0.25, 0.0, 0.0]
rpy_des = [0.0, 0.0, 0.0]
pos_des = [0.3, 0.0, 0.0]
acc_des = [15.0, 15.0, 15.0, 50.0, 50.0, 15.0]
ctrl_point = [0.15, 0.0, 0.42]
foot_pose = [-0.25, 0.0, 0.25, 0.0, 0.25, 0.0]  # 反向相位
step_height = [0.18, 0.18]
value = 0
duration = 500

[[step]]
mode = 62
gait_id = 110
contact = 15
life_count = 0
vel_des = [0.25, 0.0, 0.0]
rpy_des = [0.0, 0.0, 0.0]
pos_des = [0.3, 0.0, 0.0]
acc_des = [15.0, 15.0, 15.0, 50.0, 50.0, 15.0]
ctrl_point = [0.15, 0.0, 0.42]
foot_pose = [0.25, 0.0, 0.0, 0.0, 0.0, 0.0]  # 复位相位
step_height = [0.18, 0.18]
value = 0
duration = 500

[[step]]
mode = 7 #Puredamper
gait_id = 0
contact = 0
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 4000

